### ISSUE TITLE
"url" parameter is valid but image type is not allowed

### ISSUE THREAD

**Issue by rahulit1991** [milliHQ/terraform-aws-next-js#297]
Hello team,

Thanks for your awesome contribution to this stack. I am facing one issue with the latest version of this stack. Here is an issue:

https://uat-webv3.whimstay.com/_next/image?url=%2Fimage%2Ficons%2Fguest.svg&w=48&q=75

Is anything needed to take care of in the latest version? I am not able to load some images. It's throwing an error of 400 in the network tab with the response '"URL" parameter is valid but image type is not allowed. '

Can you please help with this?

Thanks

**Comment by ofhouse** [comment]
Hi,
since the latest version uses the Image Optimizer of Next.js 12.1.0 SVGs are no longer automatically optimized.
To keep SVG optimized, you have to add [the following configuration](https://nextjs.org/docs/api-reference/next/image#dangerously-allow-svg) to the `next.config.js`:
```js
module.exports = {
  images: {
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
}
```

However I see that we forgot to pass the new configuration properties to the underlying [Image Optimization module](https://github.com/milliHQ/terraform-aws-next-js-image-optimization).
So setting the values currently has no effect, will fix this in the next release.

**Comment by ofhouse** [comment]
Sorry, the important part of my previous message was a bit lost:
> So setting the values currently has no effect, will fix this in the next release.

**Comment by rahulit1991** [comment]
Got it. Waiting for your fix and release. As we have a blocker to not going to production release till your fix is released. Hope this will be released ASAP.

**Comment by ofhouse** [comment]
This has been fixed in [`v0.12.1`](https://github.com/milliHQ/terraform-aws-next-js/releases/tag/v0.12.1), thanks for reporting!

**Comment by rahulit1991** [comment]
Thanks for the quick release. It really helped me to check my issue. But sadly, the Issue still remains the same. not resolved. 
Not able to load any SVG files on my website. 
Please check: https://uat-webv3.whimstay.com/detail/sextant-or-habitat-brickell-or-10-mins-to-beach-or-gym-pool-or-penthouse-or-3-bed-2-bath/99620?name=Miami%2CFL&adultsCount=1&childrenCount=0&suitablePet=false&whimstayPlus=true&timestamp=1649701270473

![image](https://user-images.githubusercontent.com/64314085/162805328-6cebe6a5-8e29-4dce-9064-d3730e4c4cb0.png)

Deployed with latest version.
![image](https://user-images.githubusercontent.com/64314085/162804711-1ede26d7-53c4-4b0b-b143-6696b14535c5.png)

next.config.js:
```
const withPlugins = require("next-compose-plugins")
const path = require('path');
const withBundleAnalyzer = require("@next/bundle-analyzer")({
  enabled: process.env.ANALYZE === "true",
})

const defaultConfig = {
  target: "serverless",
  swcMinify: false,
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    if (!isServer) {
      config.resolve.fallback.fs = false;
    }
    // config.sassOptions = {
    //   includePaths: [path.join(__dirname, 'src/styles')],
    // };
    return config
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  experimental: {
    optimizeFonts: true,
    modern: true,
  },
  sassOptions: {
    includePaths: [path.join(__dirname, 'src/styles')],
  },
  redirects: require("./next-redirect"),
  images: {
    domains: ["******-bucket.s3.us-east-2.amazonaws.com", "****-bucket.s3.us-east-2.amazonaws.com", "********.cloudfront.net", '*******.cloudfront.net', 's3-us-east-2.amazonaws.com'],
    // formats: ['image/avif', 'image/webp'],
    //minimumCacheTTL: 60,
    //disableStaticImages: true,
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    //layoutRaw: true,
  },
}

module.exports = withPlugins([withBundleAnalyzer], defaultConfig)
```

Is anything missing from myend?

**Comment by ofhouse** [comment]
Did you also updated the `tf-next` builder in the `package.json` to the latest version?

Can you check the content of the `.next-tf/config.json` that is generated after running `tf-next build?`

The file is used as input for the Terrafom module and the values of `dangerouslyAllowSVG` & `contentSecurityPolicy` are taken from there.
So if the values are not present in this file this could indicate that you are using the wrong version of `tf-next` or that something is still broken on our end.
